### ISSUE TITLE
Have common Vocabularies compiled into the library

### ISSUE THREAD

**Issue by tonicebrian** [robstewart57/rdf4h#107]
I'm working in an application using SKOS and it would be super handy if common terms for SKOS were part of the library so I could use autocomplete and type check everything so common misspellings don't sneak in. I'm wondering if creating Vocabularies at least for the ones in `standard_namespaces` would be of interest to `rdf4h`.

I'm thinking about contributing something like what rdf4j has in https://github.com/eclipse/rdf4j/tree/master/core/model-vocabulary/src/main/java/org/eclipse/rdf4j/model/vocabulary

**Comment by robstewart57** [comment]
Hi @tonicebrian good idea, and this has been something I've been meaning to add to this library. For SKOS, and other commonly used vocabularies.

I will reply to you here when I've added this functionality.

**Comment by tonicebrian** [comment]
Hi Rob, I'm willing to contribute this myself. If you have some ideas about structure, just put here a minimal template/structure and I will follow it. Otherwise I could do a "proposal" for SKOS and discuss that in the PR.

I'm planning to use rdf4h in a project and the missing things in the library are short term the vocabularies and long term the ability to work with Namedgraphs, so I'd prefer that you expend your time working on harder issues 😄

**Comment by tonicebrian** [comment]
Hey, @robstewart57 did you like the structure I picked for the Vocabularies in #108 . I could do the same for all other standard vocabularies but if you think it doesn't belong here, I can create a library just with the vocabularies in it and just depend on `rdf4h`

**Comment by robstewart57** [comment]
Hi @tonicebrian Thanks for the proposal.

> I could do the same for all other standard vocabularies but if you think it doesn't belong here, I can create a library just with the vocabularies in it and just depend on rdf4h

Take a look at @fabianmeyer 's [rdf4h-vocabulary-generator](https://github.com/fabianmeyer/rdf4h-vocabulary-generator) and  [rdf4h-vocabulary](https://github.com/fabianmeyer/rdf4h-vocabulary) packages. The approach uses template Haskell to read a schema from a Turtle file, and generates a Haskell module at compile time e.g.

    $(genVocabulary "resources/shacl.ttl")

The two advantages I see are:

1. You don't have to implement the Haskell modules by hand for each vocabulary.
2. You avoid mistakes  e.g. typo mistakes in URIs, property strings, etc.

Two possible disadvantages are:

1. You are committed to the choices made by the implementation of `genVocabulary`, which might not meet your needs.
2. If you wanted to use this template Haskell technique for your own schemas, then you only get the module at compile time, limiting the ability to inspect it during development and IDE features e.g.

> it would be super handy if common terms for SKOS were part of the library so I could use autocomplete

in which case you'd need to compile your SKOS vocab module with `genVocabulary` first, then develop another module that uses `SKOS.hs`.

@tonicebrian does [rdf4h-vocabulary-generator](https://github.com/fabianmeyer/rdf4h-vocabulary-generator) meet your needs?

**Comment by tonicebrian** [comment]
Hi @robstewart57 yes, I on paper it solves completely what I was looking for. But I tried to compile it and I get compilation errors so maybe it is abandoned.

```
rdf4h-vocabulary          > /home/cebrian/GIT/rdf4h-vocabulary/src/Data/RDF/Vocabulary/XSD.hs:1:1: error:
rdf4h-vocabulary          >     Exception when trying to run compile-time code:
rdf4h-vocabulary          >       ParseFailure "Parse failure: \n(line 7, column 2):\nunexpected Cannot resolve IRI: Scheme head: not enough input (Nothing,Nothing,\"\")\nexpecting subject resource"
rdf4h-vocabulary          > CallStack (from HasCallStack):
rdf4h-vocabulary          >   error, called at src/Data/RDF/Vocabulary/Generator/VocabularyGenerator.hs:24:23 in rdf4h-vocabulary-generator-0.1.0.0-2J3xItsPFIeIMGirmv8qwN:Data.RDF.Vocabulary.Generator.VocabularyGenerator
rdf4h-vocabulary          >     Code: genVocabulary "resources/xsd.ttl"
```
I'll have a closer look if I have time, but for this ticket I think you can close it. Either requires a fix to that repo or to create a tool along these lines.

**Comment by koslambrou** [comment]
@robstewart57 Do you think those packages should be integrated into `rdf4h` or kept in a separate repository ?

**Comment by robstewart57** [comment]
@tonicebrian in your clone of `rdf4h-vocabulary`, change `resources/xsd.ttl`.

Change line 7 from:

    <> rdfs:label "XSD Namespace Document";

to:

    xsd: rdfs:label "XSD Namespace Document";

Then try compiling.

**Comment by robstewart57** [comment]
@koslambrou

> Do you think those packages should be integrated into rdf4h or kept in a separate repository ?

I've thought about that too. The author of the packages, @fabianmeyer , has previously indicated this would be fine.

The main issue I see is the added `template-haskell` dependency `rdf4h-vocabulary-generator` would bring into `rdf4h`. But since stackage now stores pre-compiled packages, this is perhaps a lower cost to compile times it would have been in the past. It also depends on `classy-prelude`, but I assume that could be removed if these two libraries are absorbed into the `rdf4h` library.

Compiling the actual `RDFS.hs`, `XSD.hs`, `SHACL.hs` etc modules takes ~10 seconds, so not a huge cost.

**Comment by tonicebrian** [comment]
Hi @robstewart57 that solved the problem.

@koslambrou and @robstewart57 if you accept a suggestion, I think it would be a super good addition to rdf4h. First because coming myself from rdf4j I was expecting something similar here (or at least a clear sign pointing to those libraries). And if you are going to include them in the library, please unroll symbols from template haskell into regular Haskell source code files. When I was looking for a functionality like this one I was looking for autocomplete and to avoid silly typos when coding applications.

**Comment by robstewart57** [comment]
@tonicebrian @koslambrou This has been implemented in the `schema-vocab` branch with this commit: https://github.com/robstewart57/rdf4h/commit/b3463e7af3c19d74c93e22f5c75dc02355535f1c

@tonicebrian when you build the rdf4h library now (on the `schema-vocab` branch), it will create and compile some additional modules:

- Data.RDF.Vocabulary.DCTerms
- Data.RDF.Vocabulary.OWL
- Data.RDF.Vocabulary.RDF
- Data.RDF.Vocabulary.RDFS
- Data.RDF.Vocabulary.SHACL
- Data.RDF.Vocabulary.VANN
- Data.RDF.Vocabulary.XSD

Your IDE's auto-complete support should be able to find these modules. If you run the haddock tool you should also be able to generate HTML documentation for these Haskell modules that are generated at compile time. E.g. if using stack, then `stack haddock`, which prints the filepath to the `index.html` HTML file for rdf4h.

Adding more common schemas to rdf4h should just be a case of adding a Turtle schema file in the `resources/` directory and creating a stub Haskell module in `Data.RDF.Vocabulary`. Or you can also use the `genVocabulary` Template Haskell function in your own application code.

Does this work for you?

**Comment by tonicebrian** [comment]
Hey @robstewart57 yes, this works for me. If you could please add FOAF and SKOS to this first PR it would be super nice.

**Comment by robstewart57** [comment]
@tonicebrian done https://github.com/robstewart57/rdf4h/pull/110 .
