### ISSUE TITLE
Parser not handling correct turtle file

### ISSUE THREAD

**Issue by AlexandruIstrate** [robstewart57/rdf4h#113]
I have the following turtle file
```ttl
<http://www.cw.org/#problem2><http://www.cw.org/testPredA> false .
<http://www.cw.org/#problem2><http://www.cw.org/testPredA> true .
<http://www.cw.org/#problem2><http://www.cw.org/testPredB> true .
<http://www.cw.org/#problemNot2><http://www.cw.org/testPredB> false .
<http://www.cw.org/#problemNot2><http://www.cw.org/testPredB> true .
<http://www.cw.org/notpprefix/subjectC><http://www.cw.org/notpprefix/predicateC><http://www.cw.org/notpprefix/objectC> .
<http://www.cw.org/pprefix/subjectC><http://www.cw.org/pprefix/predicateC><http://www.cw.org/pprefix/objectC> .
<http://www.cw.org/pprefix/subjectD><http://www.cw.org/qprefix/predicateD><http://www.cw.org/qprefix/objectD> .
<http://www.cw.org/pprefix/subjectE><http://www.cw.org/rprefix/predicateE><http://www.cw.org/qprefix/objectE> .
<http://www.cw.org/prob4A><http://www.cw.org/testPredA><http://www.cw.org/prob4B> .
<http://www.cw.org/prob4B><http://www.cw.org/testPredA><http://www.cw.org/prob4C> .
<http://www.cw.org/prob4C><http://www.cw.org/testPredB><http://www.cw.org/prob4D> .
<http://www.cw.org/prob4D><http://www.cw.org/testPredB><http://www.cw.org/prob4E> .
<http://www.cw.org/prob4E><http://www.cw.org/testPredC><http://www.cw.org/prob4F> .
<http://www.cw.org/prob4F><http://www.cw.org/testPredC><http://www.cw.org/prob4A> .
<http://www.cw.org/sprefix/subjectD><http://www.cw.org/notpprefix/predicateD><http://www.cw.org/sprefix/objectD> .
<http://www.cw.org/subjectA><http://www.cw.org/predicateA><http://www.cw.org/objectA> .
<http://www.cw.org/subjectB><http://www.cw.org/predicateB><http://www.cw.org/objectB> .
<http://www.cw.org/testSubA><http://www.cw.org/hasBool> false .
<http://www.cw.org/testSubA><http://www.cw.org/hasBool> true .
<http://www.cw.org/testSubA><http://www.cw.org/hasNegInt> -50 .
<http://www.cw.org/testSubA><http://www.cw.org/hasPosInt> 50 .
<http://www.cw.org/testSubA><http://www.cw.org/hasStringLit>"literalstring" .
<http://www.cw.org/testSubA><http://www.cw.org/problem3/#predicate1> true .
<http://www.cw.org/testSubA><http://www.cw.org/problem3/#predicate4> true .
<http://www.cw.org/testSubA><http://www.cw.org/testObjList> -5 .
<http://www.cw.org/testSubA><http://www.cw.org/testObjList> 10 .
<http://www.cw.org/testSubA><http://www.cw.org/testObjList> 20 .
<http://www.cw.org/testSubA><http://www.cw.org/testPredList> -5 .
<http://www.cw.org/testSubA><http://www.cw.org/testPredList> 10 .
<http://www.cw.org/testSubA><http://www.cw.org/testPredList> 20 .
<http://www.cw.org/testSubB><http://www.cw.org/problem3/#predicate2> true .
<http://www.cw.org/testSubB><http://www.cw.org/problem3/#predicate5> true .
<http://www.cw.org/testSubC><http://www.cw.org/problem3/#predicate2> true .
<http://www.cw.org/testSubC><http://www.cw.org/problem3/#predicate3> true .
<http://www.cw.org/testSubC><http://www.cw.org/problem3/#predicate6> true .
<http://www.cw.org/tprefix/subjectE><http://www.cw.org/notpprefix/predicateE><http://www.cw.org/tprefix/objectE> .
```

And when I try the `TurtleParser` I get the following error:
```
Parse failure: 
(line 7, column 75):
unexpected "<"
expecting whitespace-or-comment
```
Why is this happening when my Turtle file is completely valid?

**Comment by tmciver** [comment]
While you turtle document does indeed seem to validate when I check it with the [IDLab Turtle Validator](http://ttl.summerofcode.be/), it does not seem to conform to [the spec](https://www.w3.org/TR/turtle/#simple-triples) where it is indicated that there must be a space between the elements of the triples.

**Comment by AlexandruIstrate** [comment]
> While you turtle document does indeed seem to validate when I check it with the [IDLab Turtle Validator](http://ttl.summerofcode.be/), it does not seem to conform to [the spec](https://www.w3.org/TR/turtle/#simple-triples) where it is indicated that there must be a space between the elements of the triples.

I noticed that adding spaces makes it work. Could you tell me where exactly in the spec it says that there must be a space between the elements of the triples? - I can't find it.

**Comment by tmciver** [comment]
Sure. I had included the link in my comment but here it is again: https://www.w3.org/TR/turtle/#simple-triples.Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: AlexandruIstrate ***@***.***> Date: 4/8/22  3:04 AM  (GMT-05:00) To: robstewart57/rdf4h ***@***.***> Cc: Tim McIver ***@***.***>, Comment ***@***.***> Subject: Re: [robstewart57/rdf4h] Parser not handling correct turtle file (Issue #113) 

While you turtle document does indeed seem to validate when I check it with the IDLab Turtle Validator, it does not seem to conform to the spec where it is indicated that there must be a space between the elements of the triples.

I noticed that adding spaces makes it work. Could you tell me where exactly in the spec it says that there must be a space between the elements of the triples? - I can't find it.

**Comment by AlexandruIstrate** [comment]
Yeah, my dude, no idea what that was. I don't think I ended up using your thing after all. It was for some uni project anyway (which I got a huge mark in because some guy liked coding and did the whole thing your library does by hand 😆).

Appreciate the dedication to reply after 6 months though.

**Comment by tmciver** [comment]
Wow, that's strange.  I had replied to you on April 8th using my phone and it only posted here on October 11th!  I guess I won't do that again.
