### ISSUE TITLE
W3C test suite

### ISSUE THREAD

**Issue by cordawyn** [robstewart57/rdf4h#17]
I suggest we discuss implementing W3C test suite in this thread.
It is currently developed in my repository, in "w3tests" branch: https://github.com/cordawyn/rdf4h/tree/w3tests

**Comment by ddssff** [comment]
RDF newbie here - how concerned should I be about these failures?

**Comment by robstewart57** [comment]
Hi @ddssff 

These failing cases are corner cases for the N3, TTL and RDF/XML parsers. This unit test suite is the one specified by the W3C RDF specification. It's on my TODO list to squish these parser bugs in the next month or so.

As a side point, I notice that you clones from amccausl/RDF4H . The upstream version of RDF4H is this repository at https://github.com/robstewart57/rdf4h .

Do please create Github issues to track any bugs you encounter with RDF4H.

**Comment by gkellogg** [comment]
When I can carve out some time, I'd like to get these added to our copies of the various language test suites.

**Comment by ddssff** [comment]
Thanks, I found the newer repo a few minutes later.  I will be in touch.

**Comment by cordawyn** [comment]
@robstewart57 Rob, I'm trying the latest stuff from master branch, but the tests (`stack test`) seem to fail, because the turtle parser fails to parse the manifest files. I tried this in ghci:
```
*Data.RDF> let f = parseFile (TurtleParser (Just $ BaseUrl "") Nothing) "data/w3c/turtle/TurtleTests/manifest.ttl" :: IO (Either ParseFailure TriplesGraph)
*Data.RDF> f
Left (ParseFailure "(line 18, column 2):\nunexpected Invalid URI in Turtle parser: \"\"\nexpecting subject resource")
```
And it seems to stumble while reading the manifest file:
```
...
<>  rdf:type mf:Manifest ;
...
```

**Comment by robstewart57** [comment]
An update.. For e62e7145612e9756fa14e0d7f33eb77a7bb1e974 across all tests, i.e. API property and test cases and the W3C test cases:

```
         Properties   Test Cases    Total        
 Passed  61           482           543          
 Failed  2            122           124          
 Total   63           604           667
```

Which is down from about 180 failing test cases a few months ago, prior to the current round of test driven development, so progress is good if a little steady.

**Comment by robstewart57** [comment]
The current W3C test results are:

* NTriples

    stack test --test-arguments="--pattern /parser-w3c-tests-ntriples/"

All 136 tests passed (0.14s)

* Turtle

    stack test --test-arguments="--pattern /parser-w3c-tests-turtle/"

All 596 tests passed (1.17s)

* RDF/XML

    stack test --test-arguments="--pattern /parser-w3c-tests-xml/"

47 out of 162 tests failed (1.03s)

I will close this issue ticket once all RDF/XML parser bugs have been fixed.

**Comment by robstewart57** [comment]
This library finally has 100% compliance with the W3c tests in `rdf-tests` for parsing NTriples, Turtle and RDF/XML :+1: 

> All 1099 tests passed (1.47s)

https://travis-ci.org/robstewart57/rdf4h

Thanks to @wismill for the Turtle parser and XML parser bug fixes!

This compliance is reflected in release 4.0.0 of this library.
