### ISSUE TITLE
Push 1.3.1 to hackage

### ISSUE THREAD

**Issue by menelaos** [robstewart57/rdf4h#24]
See title, basically a follow-up to https://github.com/robstewart57/hsparql/issues/13.

**Comment by robstewart57** [comment]
Whilst that's compiling, I'd be very interested in knowing what you're up to with hsparql and rdf4h?

**Comment by robstewart57** [comment]
Version 1.3.1 is now on hackage.

**Comment by menelaos** [comment]
Perfect, thanks! I'm just exploring some of the semantic web options in Haskell, no real project yet.
