### ISSUE TITLE
turtle serializer does not properly deal with prefixes

### ISSUE THREAD

**Issue by andrewufrank** [robstewart57/rdf4h#27]
dear robert
the bug which lead to the long discussion in the other bug report was hitting me again today. the error is very simply in the turtle serializer code: the code expects a map from url to prefix (not prefix to url - it is reversed in a function a bit above, for reasons i do not understand). then the test for the match of the prefix must be with the second element (not the first). i changed from (k,_) to (_,k) and it works.
can you check my fix and put it into the repository? thank you!

-- Expects a map from uri to prefix, and returns the (prefix, uri_expansion)
-- from the mappings such that uri_expansion is a prefix of uri, or Nothing if
-- there is no such mapping. This function does a linear-time search over the 
-- map, but the prefix mappings should always be very small, so it's okay for now.
findMapping :: Map T.Text T.Text -> T.Text -> Maybe (T.Text, T.Text)
findMapping pms uri =
  case mapping of
    Nothing     ->  Nothing
    Just (u, p) -> Just (p, T.drop (T.length u) uri) -- empty localName is permitted
  where
    mapping        = find ((_, k) -> T.isPrefixOf k uri) (Map.toList pms)
-- exchanged _ and k: the map is from uri to prefix, check for  k match as prefix to uri
-- it was reversed in writeTriples

**Comment by andrewufrank** [comment]
there is a second effect of the same confusion in the line with just. the length T.length must be taken from the prefix, not the u. it also does not drop the ":", the drop must be the length +1. with these changes it seems to work for me 

the code i have currently
    Just (u, p) -> Just (p, T.drop (1+T.length p) uri) -- empty localName is permitted

no extensive testing.
thank you!

**Comment by andrewufrank** [comment]
there is still a problem that two prefixes with the same start (i.e. rdf and rdfs) conflic  - the find finds the first (shorter one) and replaces rdfs:zzz by rdf::zzz. 
to fix this, i propose to add the ":" to the prefix when reversing the prefix mapping:
writeTriples :: Handle -> Maybe T.Text -> PrefixMappings -> Triples -> IO ()
writeTriples h mdUrl (PrefixMappings pms) ts =
  mapM_ (writeSubjGroup h mdUrl revPms) (groupBy equalSubjects ts)
  where
    revPms = Map.fromList $ map (\(k,v) -> (v,(T.append k ":")))   $ Map.toList pms
-- af added the : to the prefix             


and then not adding the ":" when producing the output:
writeUNodeUri :: Handle -> T.Text -> Map T.Text T.Text -> IO ()
writeUNodeUri h uri prefixes = do 
--  putStrLn . unwords $  ["writeUNodeUri mapping is ", show mapping ]
  case mapping of
    Nothing                 -> hPutChar h '<' >> T.hPutStr h uri >> hPutChar h '>'
    (Just (pre, localName)) -> T.hPutStr h pre >>  T.hPutStr h localName
    -- the prefix includes the : 
--    (Just (pre, localName)) -> T.hPutStr h pre >> hPutChar h ':' >> T.hPutStr h localName
  where
    mapping         = findMapping prefixes uri

and at the end not adding 1 to the T.length (as suggested in the previous comment): 

findMapping :: Map T.Text T.Text -> T.Text -> Maybe (T.Text, T.Text)
findMapping pms uri =
  case mapping of
    Nothing     -> Nothing 
    Just (u, p) -> Just (p, T.drop (T.length p) uri) -- empty localName is permitted
  where
    mapping        = find (\(_, k) -> T.isPrefixOf k uri) (Map.toList pms)
-- exchanged _ and k: the map is from uri to prefix, check for  k match as prefix to uri
-- it was reversed in writeTriples 

-- i hope this is now really fixing the issues (i have not extensively tested, especially not with a null prefix)

**Comment by robstewart57** [comment]
Hi Andrew, thank you for opening this ticket! I'll take a look into this.

**Comment by andrewufrank** [comment]
dear robert
i work more on this code for the next weeks. what is the prefered format
for you that i communicate  suggestions for improvement. are you working
with the code on github? if so, i could try to learn how to use github...

thank you for your efforts!
andrew

Prof. Dr. sc.techn. Dr. h.c. Andrew U. Frank
				 +43 1 58801 12710 direct
Geoinformation, TU Wien          +43 1 58801 12700 office
Gusshausstr. 27-29               +43 1 55801 12799 fax
1040 Wien Austria                +43 676 419 25 72 mobil

**Comment by robstewart57** [comment]
Hi Andrew, yes github is the most upto date verion of this library. As it happens, I'm due to give a talk about this library in the next couple of months, which will probably result in some refactoring and almost certainly a slightly different API design. I'll let you know. Also, yes, github is the best place to communicate (openly) about the library, about the API, and about bugs you find. And of course I will look into the issues you report above. Out of interest, what are you using the library for?

**Comment by andrewufrank** [comment]
the project at the moment is to used rdf to encode treebank tags (from
natuarl language processing software, like stanford corenlpP) and then
extract spatial movements from literary text.
interesting and challenging.
i use 4store as the triple engine. what are you using?

andrew

**Comment by wismill** [comment]
Is this issue still not fixed?

**Comment by tmciver** [comment]
I have a branch which adds a couple of tests that expose the bugs discussed above as well as fixes that make the tests pass.  You can see the changes so far [here](https://github.com/robstewart57/rdf4h/compare/master...tmciver:issue-27).  I want to validate these changes before submitting a PR; I'd also like to make a couple of additional improvements before merging.

**Comment by tmciver** [comment]
@robstewart57 Do you have any thoughts on my changes for this issue?

**Comment by robstewart57** [comment]
hi @tmciver , thanks for this!

Apart from the one code review comment I've just sent, this looks good for a PR.

**Comment by tmciver** [comment]
Thanks!  Feel free to close the issue if you feel it's been resolved.

**Comment by robstewart57** [comment]
@tmciver @andrewufrank closed.
