### ISSUE TITLE
Turtle parser does not restore subject context after parsing RDF collections

### ISSUE THREAD

**Issue by fabianmeyer** [robstewart57/rdf4h#37]
When parsing a RDF collection, the turtle parser does not restore the subject context. Hence, all further predicate-object tupels are added to the last list node of the created collection:

Example:
```
@prefix : <http://example.org/foo#> .
:subject
  :predicate1 ( :a ) ;
  :predicate2 :b .
```
The parser will add `:predicate2 :b` to the last list blank node instead of the `:subject`.

**Comment by robstewart57** [comment]
Fixed by https://github.com/fabianmeyer/rdf4h/commit/52b2906bbbe6ae85323a485640f20388dbfe7f76

**Comment by fabianmeyer** [comment]
There also seems to be an issue with blank nodes inside of collections:

```
@prefix : <http://example.org/foo#> .
:subject
  :predicate1 ( [
    :predicate3 :a
  ] ) ;
  :predicate2 :b .
```
Adds the `:predicate2 :b` to the list node:

```
Triple (UNode "http://example.org/foo#subject") (UNode "http://example.org/foo#predicate1") (BNodeGen 1)
Triple (BNodeGen 1) (UNode "http://example.org/foo#predicate2") (UNode "http://example.org/foo#b")
Triple (BNodeGen 1) (UNode "http://www.w3.org/1999/02/22-rdf-syntax-ns#first") (BNodeGen 2)
Triple (BNodeGen 2) (UNode "http://example.org/foo#predicate3") (BNodeGen 3)
Triple (BNodeGen 2) (UNode "http://www.w3.org/1999/02/22-rdf-syntax-ns#rest") (UNode "http://www.w3.org/1999/02/22-rdf-syntax-ns#nil")
Triple (BNodeGen 3) (UNode "http://www.w3.org/1999/02/22-rdf-syntax-ns#first") (UNode "http://example.org/foo#a")
```

Unfortunately, I'm not quite sure about the cause and how to fix it. Perhaps a missing popped subject-context somewhere else?

**Comment by robstewart57** [comment]
OK. I don't have a chance to look at this just now, so I've added it as a failing unit test:

https://github.com/robstewart57/rdf4h/commit/a98cb772e6e940866d5801f14e9fc7808ddce383

Which can be run with:

    stack test --test-arguments="--pattern conformance-turtle-example10"
