### ISSUE TITLE
typedL does not produce acceptable triple for integer 0

### ISSUE THREAD

**Issue by andrewufrank** [robstewart57/rdf4h#41]
the function typedL applied to a value of 0 and a schema `"http://www.w3.org/2001/XMLSchema#integer"`  produces an empty string, not "0"; the empty string is not an acceptable value for an integer according to `https://www.w3.org/TR/xmlschema-2/#integer`.
The problem originates with the lines 

    _integerStr, _decimalStr, _doubleStr :: T.Text -> T.Text
    _integerStr = T.dropWhile (== '0')

which consumes all zeros from "0".
I think a conversion using printf would be simpler?
`

**Comment by robstewart57** [comment]
Thanks, fixed in https://github.com/robstewart57/rdf4h/commit/525b666f480ea5d2a11560aa637ccc6de3ea56ad .
