### ISSUE TITLE
URI validity check

### ISSUE THREAD

**Issue by defanor** [robstewart57/rdf4h#45]
`Data.RDF.Types.isAbsoluteURI` assumes that the URI will be valid (and uses `fromJust`), which is not guaranteed to be the case. The functions that use it directly also don't seem to allow a failure. Perhaps everything affected should be wrapped into `Maybe`, or something that would report the cause of a failure, in order to save potential debugging effort when it happens.

**Comment by wismill** [comment]
I have worked on this in #55

**Comment by defanor** [comment]
Thanks for the suggestion, though checking input string with `uriValidate` before other manipulations would still be a rather error-prone approach. But `isAbsoluteUri` was indeed changed in #55: it doesn't use `fromJust` anymore. So yes, closing the issue, and thanks for fixing it.
