### ISSUE TITLE
Examples don't work

### ISSUE THREAD

**Issue by JonathanReeve** [robstewart57/rdf4h#47]
Unless I'm missing something, the ParseURLs example casts the result as a TriplesList, which doesn't seem to be exposed anywhere.

**Comment by robstewart57** [comment]
Hi @JonathanReeve, which file are you talking about? Thanks!

**Comment by JonathanReeve** [comment]
The ParseURLs example: [examples/ParseURLs.hs](https://github.com/robstewart57/rdf4h/blob/master/examples/ParseURLs.hs). Maybe the other ones, too?  Although I haven't tested those.

**Comment by robstewart57** [comment]
@JonathanReeve thanks. fixed in https://github.com/robstewart57/rdf4h/commit/4bf40bee6aeb2465d75236b2bc03b42cab5fd6ef .
