### ISSUE TITLE
XMLParser doesn't seem to recognize blank nodes

### ISSUE THREAD

**Issue by JonathanReeve** [robstewart57/rdf4h#48]
I posted [a question on stackoverflow](https://stackoverflow.com/questions/49600974/in-rdf4h-haskell-how-can-i-get-missing-triples?noredirect=1#comment86213717_49600974) about this recently. Basically, if you have an XML data structure like this: 

```xml
    <pgterms:bookshelf>
      <rdf:Description rdf:nodeID="N8d8ab517be5d4d24a574a79c302445fc">
        <dcam:memberOf rdf:resource="2009/pgterms/Bookshelf"/>
        <rdf:value>Napoleonic(Bookshelf)</rdf:value>
      </rdf:Description>
    </pgterms:bookshelf>
```

It seems to be completely ignored by RDF4H. The blank nodes show up if I first convert the XML file to a Turtle file.

**Comment by robstewart57** [comment]
I've added this as unit test in `data/xml/example22.rdf` and `data/xml/example22.out` in https://github.com/robstewart57/rdf4h/commit/e6114135bc80686a52cc6a9a9e2aae7ac337f8a3 .

Indeed it currently fails:

    stack test --test-arguments="--pattern conformance-xml-example22"
    Progress: 1/2rdf4h tests
    parser-unit-tests-xml
    conformance-xml-example22
      loading-expected-graph-data: OK (0.02s)
      loading-input-graph-data:    OK (0.02s)
      comparing-graphs:            FAIL
        Exception: user error (Graph xml-example22 not equivalent to expected:
        Expected:
          Triple (UNode "http://njh.me/ebooks/15233") (UNode "http://www.gutenberg.org/2009/pgterms/bookshelf") (BNode "_:genid1")
        Found:
          Triple (UNode "ebooks/15233") (UNode "http://www.w3.org/1999/02/22-rdf-syntax-ns#type") (UNode "http://www.gutenberg.org/2009/pgterms/ebook")
        )

    1 out of 3 tests failed (1.17s)    

Thanks for the bug report!

**Comment by robstewart57** [comment]
@JonathanReeve This test passes now as of https://github.com/robstewart57/rdf4h/commit/d7518cf9913d2ed2b80fb32d54fcb7edcd4fce95 .

Note that this RDF/XML parser is still not a complete implementation, since it fails 41 of the 162 W3C unit tests for RDF/XML parsers.
