### ISSUE TITLE
Backslash character parser bugs in NTriples parser

### ISSUE THREAD

**Issue by robstewart57** [robstewart57/rdf4h#52]
let Right (g::RDF TList) =
        parseString
             NTriplesParser
             (Data.Text.pack "<http://a.example/s> <http://a.example/p> \"\\r\" .")

Evaluating g:

    Triple (UNode "http://a.example/s") (UNode "http://a.example/p") (LNode (PlainL "r"))

So the `\r` character is being parsed just as `r`.

This is the reason for a number of TurtleParser tests failing, since their results are compared against NTriple golden references parsed with the NTriples parser, e.g.

* `stack test --test-arguments="--pattern literal_with_escaped_CARRIAGE_RETURN"`
* `stack test --test-arguments="--pattern literal_with_CHARACTER_TABULATION"`

**Comment by wismill** [comment]
Hi, this is fixed in #55
