### ISSUE TITLE
https://www.govtrack.us/data/rdf/bills.099.actions.rdf.gz no longer available

### ISSUE THREAD

**Issue by jrp2014** [robstewart57/rdf4h#61]
It might be good to have a different common benchmark.  There are some datasets here: https://www.w3.org/wiki/TaskForces/CommunityProjects/LinkingOpenData/DataSets

**Comment by robstewart57** [comment]
@jrp2014 well spotted. Yes, it looks like we'll need a new RDF source for the benchmarks.

**Comment by wismill** [comment]
How big was this dataset?

**Comment by robstewart57** [comment]
Fixed by https://github.com/robstewart57/rdf4h/commit/e1a11d70e8ed76e4e9f1a3698ba64b3a281b5b73
