### ISSUE TITLE
Remove old HXT based RDF/XML parser

### ISSUE THREAD

**Issue by robstewart57** [robstewart57/rdf4h#73]
@wismill has completely re-implemented the RDF/XML parser, using the xmlbf library. Not only is it a _correct_ implementation (passing w3c unit tests), it is also _faster_. See https://github.com/robstewart57/rdf4h/pull/67#issuecomment-498135596 .

It doesn't useful to expose both XML parsers to users. The options are:

1. Keep the `XmlParserHXT` module in this repository, for reference, but don't expose it in the cabal file.

2. Remove the `XmlParserHXT` module, i.e the `srcText/RDF/RDF4H/XmlParserHXT.hs` file.

@wismill thoughts?

**Comment by wismill** [comment]
I have completed your work using `xmlbf`, but I do not know which one of `xmlbf` and `xht` would be faster if optimised. On the other hand, having two implementation (with one of them incomplete) may be confusing for the user.

A good compromise seems the first option: not exposing `XmlParserHXT` in the cabal and keep an issue open. We could then focus on the last correctness issues before tackling performance issues.
