### ISSUE TITLE
New rdf4h release coinciding with xmlbf 0.6 release

### ISSUE THREAD

**Issue by robstewart57** [robstewart57/rdf4h#74]
The new XML parser depends on monad transformer additions added by @wismill to the xmlbf library. This dependency will be reflected in the release of 0.6 of the xmlbf library.

Once xmlbf-0.6 has been uploaded to hackage, the `stack.yaml` file for rdf4h should add xmlbf-0.6 as an extra dependency, removing the information about the xmlbf git repo and commit ID, since stack will find xmlbf-0.6 on hackage.

**Comment by wismill** [comment]
Also update the version bounds in the cabal file

**Comment by robstewart57** [comment]
There wasn't a xmlbf release reflecting the monad transformer needed by rdf4h, so instead two files `Xmlbf.hs` and `Xeno.hs` were copied into this repository, temporarily hopefully:

https://github.com/robstewart57/rdf4h/commit/7cc70978b6001e426fe9224c2334bc6a1687dd71
