### ISSUE TITLE
Fix failing Turtle parser test turtle-subm-27

### ISSUE THREAD

**Issue by robstewart57** [robstewart57/rdf4h#75]
I'm seeing two tests failing. It's the same test, and both the attoparsec and the parsec instances of `Parser` fail.

    turtle-subm-27:                                                       FAIL
              Exception: HUnitFailure (Just (SrcLoc {srcLocPackage = "main", srcLocModule = "W3C.W3CAssertions", srcLocFile = "testsuite/tests/W3C/W3CAssertions.hs", srcLocStartLine = 24, srcLocStartCol = 3, srcLocEndLine = 24, srcLocEndCol = 99})) (Reason "not isomorphic: Triple (UNode \"http://w3c.github.io/rdf-tests/turtle/a1\") (UNode \"http://w3c.github.io/rdf-tests/turtle/b1\") (UNode \"http://w3c.github.io/rdf-tests/turtle/c1\")\nTriple (UNode \"http://example.org/ns/a2\") (UNode \"http://example.org/ns/b2\") (UNode \"http://example.org/ns/c2\")\nTriple (UNode \"http://example.org/ns/foo/a3\") (UNode \"http://example.org/ns/foo/b3\") (UNode \"http://example.org/ns/foo/c3\")\nTriple (UNode \"http://example.org/ns/foo/bar#a4\") (UNode \"http://example.org/ns/foo/bar#b4\") (UNode \"http://example.org/ns/foo/bar#c4\")\nTriple (UNode \"http://example.org/ns2#a5\") (UNode \"http://example.org/ns2#b5\") (UNode \"http://example.org/ns2#c5\")\n compared with Triple (UNode \"http://www.w3.org/2013/TurtleTests/a1\") (UNode \"http://www.w3.org/2013/TurtleTests/b1\") (UNode \"http://www.w3.org/2013/TurtleTests/c1\")\nTriple (UNode \"http://example.org/ns/a2\") (UNode \"http://example.org/ns/b2\") (UNode \"http://example.org/ns/c2\")\nTriple (UNode \"http://example.org/ns/foo/a3\") (UNode \"http://example.org/ns/foo/b3\") (UNode \"http://example.org/ns/foo/c3\")\nTriple (UNode \"http://example.org/ns/foo/bar#a4\") (UNode \"http://example.org/ns/foo/bar#b4\") (UNode \"http://example.org/ns/foo/bar#c4\")\nTriple (UNode \"http://example.org/ns2#a5\") (UNode \"http://example.org/ns2#b5\") (UNode \"http://example.org/ns2#c5\")\n")

**Comment by wismill** [comment]
I think I have fixed it in 1f8bdb866a8b324e465c2ad9ca2b6a9abb71dac8. Now it is merged in master.

**Comment by robstewart57** [comment]
Fixed, this test now passes.
