### ISSUE TITLE
Parsing rdf-schema files

### ISSUE THREAD

**Issue by huseyinyilmaz** [robstewart57/rdf4h#80]
Hello,

First of all thank you for implementing this library. I got how it works pretty quickly and it helped me to solve a lot of implementation details pretty quickly.

Currently I am working on a project to generate code for `schema.org` schemas which are implemented in rdf-schema format. Here is an example:
https://raw.githubusercontent.com/schemaorg/schemaorg/master/data/releases/3.7/schema.nt

I wanted to parse this format into a schema object which will represent the class structure of rdf schema. After that, I am planing to generate code for different programming languages.

Unfortunately, I am stuck on parsing the schema. I can parse rdf schema as an rdf document like this:
```https://github.com/huseyinyilmaz/schemaorg/blob/master/library/Download.hs#L30```

This format does not represent the schema itself, instead I would have just have triples that I need to parse to a schema structure. Also it turns out that  rdf-schema documents can have references to other schema files with their internet address. So those references should also be downloaded and parsed. Here is an example

```
<http://schema.org/spatial> <http://www.w3.org/2002/07/owl#equivalentProperty> <http://purl.org/dc/terms/spatial> .
```

So my question is, does rdf4h library parse rdf-schema links to validate the documents? If not is there a plan to support rdf-schema validation?

**Comment by robstewart57** [comment]
Hi @huseyinyilmaz ,

Thanks for your interest in rdf4h!

> does rdf4h library parse rdf-schema links to validate the documents?

No.

> If not is there a plan to support rdf-schema validation?

I agree that schema validation would be an interesting idea to consider adding to rdf4h in the future.

**Comment by robstewart57** [comment]
@huseyinyilmaz you might want to keep an eye on what @joshsh is up to:

https://twitter.com/joshsh/status/1213250641990049792
