### ISSUE TITLE
Non-URI Nodes (TurtleSerializer)?

### ISSUE THREAD

**Issue by tmciver** [robstewart57/rdf4h#97]
I created the following triple:
```
triple (unode ":something") (unode "a") (unode "schema:Document")
```
and serialized it using the `TurtleSerializer`.  My expectation was that it would be serialized to
```
:something a schema:Document .
```
but it gets serialized to
```
<:something> <a> <schema:Document> .
```
Is there a way to get it to serialize properly?

**Comment by robstewart57** [comment]
@tmciver mark this as fixed by https://github.com/robstewart57/rdf4h/pull/101 ?

**Comment by tmciver** [comment]
Done.  Thanks!
